### ISSUE TITLE
Question: How can I add custom content type?

### ISSUE THREAD

**Issue by microshine** [mulesoft/amf-dotnet-tools#7]
My API returns 2 types of content types
- application/json
- application/problem+json

I've got an exception on 2nd type parsing
### Exception
```
System.Exception: No MediaTypeFormatter is available to read an object of type 'LoginPost400' from content with media type 'application/problem+json'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync(HttpContent content, Type type)
```

I found that I can add custom content type using `responseFormatters` argument in `Post` method
```cs
var client = new HvcaApiClient(httpClient);

var requestFromatter = new JsonMediaTypeFormatter();
// add snake_case resolver
DefaultContractResolver contractResolver = new DefaultContractResolver
{
    NamingStrategy = new SnakeCaseNamingStrategy()
};
requestFromatter.SerializerSettings.ContractResolver = contractResolver;

var responseFormatter = new JsonMediaTypeFormatter();
responseFormatter.SerializerSettings.ContractResolver = contractResolver;
// add application/problem+json content type
responseFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/problem+json"));

var response = await client.Login.Post(new LoginPostRequest
{
    Content = new LoginPost
    {
        UserLogin = login,
        UserPassword = password,
    },
    Formatter = requestFromatter,
}, new MediaTypeFormatter[] {
    responseFormatter
});
```

But there is a problem with a request sending. Content is always `Null`.
### AMF.tools generated client
```cs
public virtual async Task<Models.LoginPostResponse> Post(Models.LoginPostRequest request, IEnumerable<MediaTypeFormatter> responseFormatters = null)
{

    var url = "/login";

    url = url.Replace("?&", "?");

    var req = new HttpRequestMessage(HttpMethod.Post, url.StartsWith("/") ? url.Substring(1) : url);

    if (request.Headers != null)
    {
        foreach (var header in request.Headers.Headers)
        {
            req.Headers.TryAddWithoutValidation(header.Key, header.Value);
        }
    }
    if (request.RawHeaders != null)
    {
        foreach (var header in request.RawHeaders)
        {
            req.Headers.TryAddWithoutValidation(header.Key, string.Join(",", header.Value));
        }
    }
    if (request.Formatter == null)
    {
        request.Formatter = new JsonMediaTypeFormatter();
    }

    var response = await proxy.Client.SendAsync(req);
    return new Models.LoginPostResponse
    {
        RawContent = response.Content,
        RawHeaders = response.Headers,
        Formatters = responseFormatters,
        StatusCode = response.StatusCode,
        ReasonPhrase = response.ReasonPhrase,
        SchemaValidation = new Lazy<SchemaValidationResults>(() => new SchemaValidationResults(true), true)
    };
}
```

As you can see the generated code doesn't create `req.Content` from `request.Content` object

I can fix it updating generated code
```cs
req.Content = new ObjectContent(typeof(Models.LoginPost), request.Content, request.Formatter ?? new JsonMediaTypeFormatter());
```

**Comment by woodp** [comment]
thanks for spotting that @microshine. 
Do you want to do a Pull Request for the change ? Please do so on this repo: https://github.com/mulesoft-labs/raml-dotnet-tools

**Comment by woodp** [comment]
fix for this will be included in next release, please check the repo: https://github.com/mulesoft-labs/raml-dotnet-tools
